# Generated by Django 3.2 on 2021-08-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='agent')),
            ],
            options={
                'verbose_name': 'Agent',
            },
        ),
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='bassin')),
            ],
            options={
                'verbose_name': 'Bassin',
            },
        ),
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='dep')),
            ],
            options={
                'verbose_name': 'Département',
            },
        ),
        migrations.CreateModel(
            name='Drv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='drv')),
            ],
            options={
                'verbose_name': 'DRV',
            },
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Enseigne',
            },
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
                ('enseigne', models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='visio.enseigne')),
            ],
            options={
                'verbose_name': 'Ensemble',
            },
        ),
        migrations.CreateModel(
            name='Industrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Industrie',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='SegmentCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='segment_commercial')),
            ],
            options={
                'verbose_name': 'Segment Commercial',
            },
        ),
        migrations.CreateModel(
            name='SegmentMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='segment_marketing')),
            ],
            options={
                'verbose_name': 'Segment Marketing',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
        migrations.CreateModel(
            name='SousEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Sous-Ensemble',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='ville')),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='Pdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Inconnu', max_length=10, verbose_name='PDV code')),
                ('name', models.CharField(default='Inconnu', max_length=64, verbose_name='PDV')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('available', models.BooleanField(default=True)),
                ('sale', models.BooleanField(default=True, verbose_name='Ne vend pas de plaque')),
                ('redistributed', models.BooleanField(default=True, verbose_name='Redistribué')),
                ('redistributedEnduit', models.BooleanField(default=True, verbose_name='redistribué Enduit')),
                ('pointFeu', models.BooleanField(default=False, verbose_name='Point Feu')),
                ('closedAt', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de Fermeture')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.agent')),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.bassin')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.dep')),
                ('drv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.drv')),
                ('enseigne', models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='visio.enseigne')),
                ('ensemble', models.ForeignKey(default=43, on_delete=django.db.models.deletion.PROTECT, to='visio.ensemble')),
                ('segment_commercial', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visio.segmentcommercial')),
                ('segment_marketing', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visio.segmentmarketing')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visio.site')),
                ('sous_ensemble', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visio.sousensemble')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.ville')),
            ],
            options={
                'verbose_name': 'Point de Vente',
            },
        ),
        migrations.CreateModel(
            name='AgentFinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='agent_finitions')),
                ('drv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.drv')),
            ],
            options={
                'verbose_name': 'Agent Finitions',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='drv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visio.drv'),
        ),
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de Saisie')),
                ('volume', models.FloatField(blank=True, default=0.0, verbose_name='Volume')),
                ('industry', models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, to='visio.industrie')),
                ('pdv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visio.pdv')),
                ('product', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='visio.produit')),
            ],
            options={
                'verbose_name': 'Ventes',
                'unique_together': {('pdv', 'industry', 'product')},
            },
        ),
    ]
