# Generated by Django 3.2.5 on 2021-09-10 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='agent')),
            ],
            options={
                'verbose_name': 'Agent',
            },
        ),
        migrations.CreateModel(
            name='Bassin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='bassin')),
            ],
            options={
                'verbose_name': 'Bassin',
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='dep')),
            ],
            options={
                'verbose_name': 'Département',
            },
        ),
        migrations.CreateModel(
            name='Drv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='drv')),
            ],
            options={
                'verbose_name': 'DRV',
            },
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Enseigne',
            },
        ),
        migrations.CreateModel(
            name='Ensemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
                ('enseigne', models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='visioServer.enseigne')),
            ],
            options={
                'verbose_name': 'Ensemble',
            },
        ),
        migrations.CreateModel(
            name='Industrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Industrie',
            },
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
                ('json', models.CharField(default=None, max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=32, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Produit',
            },
        ),
        migrations.CreateModel(
            name='SegmentCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name='segment_commercial')),
            ],
            options={
                'verbose_name': 'Segment Commercial',
            },
        ),
        migrations.CreateModel(
            name='SegmentMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='segment_marketing')),
            ],
            options={
                'verbose_name': 'Segment Marketing',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Site',
            },
        ),
        migrations.CreateModel(
            name='SousEnsemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Inconnu', max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Sous-Ensemble',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='ville')),
            ],
            options={
                'verbose_name': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGeo', models.IntegerField(blank=True, default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreeNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default=None, max_length=32, unique=True)),
                ('name', models.CharField(default=None, max_length=32, unique=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visioServer.treenavigation')),
            ],
        ),
        migrations.CreateModel(
            name='Pdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='Inconnu', max_length=10, verbose_name='PDV code')),
                ('name', models.CharField(default='Inconnu', max_length=64, verbose_name='PDV')),
                ('latitude', models.FloatField(default=0.0, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=0.0, verbose_name='Longitude')),
                ('available', models.BooleanField(default=True)),
                ('sale', models.BooleanField(default=True, verbose_name='Ne vend pas de plaque')),
                ('redistributed', models.BooleanField(default=True, verbose_name='Redistribué')),
                ('redistributedEnduit', models.BooleanField(default=True, verbose_name='redistribué Enduit')),
                ('pointFeu', models.BooleanField(default=False, verbose_name='Point Feu')),
                ('closedAt', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de Fermeture')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visioServer.agent')),
                ('bassin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visioServer.bassin')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visioServer.dep')),
                ('drv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visioServer.drv')),
                ('enseigne', models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='visioServer.enseigne')),
                ('ensemble', models.ForeignKey(default=43, on_delete=django.db.models.deletion.PROTECT, to='visioServer.ensemble')),
                ('segmentCommercial', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visioServer.segmentcommercial')),
                ('segmentMarketing', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visioServer.segmentmarketing')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visioServer.site')),
                ('sousEnsemble', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visioServer.sousensemble')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visioServer.ville')),
            ],
            options={
                'verbose_name': 'Point de Vente',
            },
        ),
        migrations.CreateModel(
            name='DashboardTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default=None, max_length=32)),
                ('dashboards', models.ManyToManyField(to='visioServer.Dashboard')),
                ('level', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='visioServer.treenavigation')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='layout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='visioServer.layout'),
        ),
        migrations.CreateModel(
            name='AgentFinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='agent_finitions')),
                ('drv', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visioServer.drv')),
            ],
            options={
                'verbose_name': 'Agent Finitions',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='drv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visioServer.drv'),
        ),
        migrations.CreateModel(
            name='Ventes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date de Saisie')),
                ('volume', models.FloatField(blank=True, default=0.0, verbose_name='Volume')),
                ('industry', models.ForeignKey(default=17, on_delete=django.db.models.deletion.PROTECT, to='visioServer.industrie')),
                ('pdv', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='visioServer.pdv')),
                ('product', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='visioServer.produit')),
            ],
            options={
                'verbose_name': 'Ventes',
                'unique_together': {('pdv', 'industry', 'product')},
            },
        ),
    ]
