# Generated by Django 3.2.5 on 2021-09-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visioServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='json',
            field=models.CharField(default=None, max_length=2048),
        ),
    ]
