# Generated by Django 3.2 on 2021-08-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visioServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdv',
            old_name='segment_commercial',
            new_name='segmentCommercial',
        ),
        migrations.RenameField(
            model_name='pdv',
            old_name='segment_marketing',
            new_name='segmentMarketing',
        ),
    ]
