# Generated by Django 3.2.5 on 2021-09-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visioServer', '0002_alter_layout_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=32, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='layout',
            old_name='json',
            new_name='matrixJson',
        ),
        migrations.CreateModel(
            name='WidgetParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=32)),
                ('subTitle', models.CharField(default=None, max_length=32)),
                ('kwargs', models.CharField(default=None, max_length=64)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visioServer.widget')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='widgets',
            field=models.ManyToManyField(to='visioServer.WidgetParams'),
        ),
    ]
