# Generated by Django 3.2 on 2021-08-30 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visioServer', '0002_auto_20210825_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=64, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pdv',
            old_name='sous_ensemble',
            new_name='sousEnsemble',
        ),
        migrations.CreateModel(
            name='TreeNavigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default=None, max_length=32, unique=True)),
                ('name', models.CharField(default=None, max_length=32, unique=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visioServer.treenavigation')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default=None, max_length=32)),
                ('dashboards', models.ManyToManyField(to='visioServer.Dashboard')),
                ('level', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='visioServer.treenavigation')),
            ],
        ),
    ]
