# Generated by Django 3.2.5 on 2021-09-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visioServer', '0003_auto_20210910_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='matrixJson',
            new_name='template',
        ),
    ]
