# Generated by Django 3.2.5 on 2021-09-10 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visioServer', '0004_rename_matrixjson_layout_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='widgets',
            new_name='widgetParams',
        ),
    ]
